page 58159 "Meeting Plan Card"
{
    ApplicationArea = All;
    Caption = 'Meeting Plan Card';
    PageType = Card;
    SourceTable = "Meeting Plans";

    layout
    {
        area(Content)
        {
            group(General)
            {
                Caption = 'General';
                Editable = not IsPosted; // Group-level editable allows dynamic expressions

                field("Id"; Rec."Id")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the unique identifier for the meeting plan automatically generated by number series.';
                }
                field("Committee Id"; Rec."Committee Id")
                {
                    ApplicationArea = All;
                    ToolTip = 'Select the board committee for this plan.';

                    trigger OnValidate()
                    begin
                        CurrPage.Update(true);
                    end;
                }
                field("Committee Description"; Rec."Committee Description")
                {
                    ApplicationArea = All;
                    ToolTip = 'Shows the description of the selected committee.';
                    QuickEntry = false;
                }
                field("Title"; Rec."Title")
                {
                    ApplicationArea = All;
                    ShowMandatory = true;
                    ToolTip = 'Enter the title of the meeting plan.';
                }
                field("Year"; Rec."Year")
                {
                    ApplicationArea = All;
                    ShowMandatory = true;
                    ToolTip = 'Enter the plan year.';
                }
                field("Quarter"; Rec."Quarter")
                {
                    ApplicationArea = All;
                    ShowMandatory = true;
                    ToolTip = 'Select the plan quarter.';
                }
                field("Status"; Rec."Status")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the lifecycle status of the meeting plan.';
                }
                field("Description"; Rec."Description")
                {
                    ApplicationArea = All;
                    MultiLine = true;
                    ToolTip = 'Enter additional descriptions or objectives for this plan.';
                }
                field(Posted; Rec.Posted)
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies whether the meeting plan has been published to the portal.';
                }
            }

            part(DateOptions; "Meeting Date Options Subform")
            {
                ApplicationArea = All;
                SubPageLink = "Meeting Plan Id" = field("Id");
                Editable = not IsPosted;
            }

            group(PollResults)
            {
                Caption = 'Live Poll Votes';

                part(PollVotes; "Meeting Date Polls Subform")
                {
                    ApplicationArea = All;
                    Provider = DateOptions;
                    SubPageLink = "Meeting Plan Id" = field("Meeting Plan Id"),
                                  "Meeting Date Option Id" = field("Id");
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(PostPlan)
            {
                ApplicationArea = All;
                Caption = 'Post / Publish to Portal';
                Image = PostOrder;
                Enabled = not IsPosted;
                Promoted = true;
                PromotedCategory = Process;
                PromotedIsBig = true;
                PromotedOnly = true;
                ToolTip = 'Publish this meeting plan to the board portal.';

                trigger OnAction()
                var
                    ConfirmQst: Label 'Do you want to proceed publishing to portal?';
                    SuccessMsg: Label 'Meeting Plan %1 has been published successfully.', Comment = '%1 = Plan Id';
                begin
                    Rec.TestField(Posted, false);

                    if not Confirm(ConfirmQst, false) then
                        exit;

                    Rec.Posted := true;
                    Rec.Status := Rec.Status::Posted;
                    Rec.Modify(true);

                    SetControlAppearance();
                    CurrPage.Update(true);
                    Message(SuccessMsg, Rec."Id");
                end;
            }
        }
    }

    trigger OnAfterGetRecord()
    begin
        SetControlAppearance();
    end;

    trigger OnAfterGetCurrRecord()
    begin
        SetControlAppearance();
    end;

    local procedure SetControlAppearance()
    begin
        IsPosted := Rec.Posted;
    end;

    var
        IsPosted: Boolean;
}