page 58159 "Meeting Plan Card"
{
    ApplicationArea = All;
    Caption = 'Meeting Plan Card';
    PageType = Card;
    SourceTable = "Meeting Plans";

    layout
    {
        area(Content)
        {
            group(General)
            {
                Caption = 'General';

                field("Id"; Rec."Id")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the unique identifier for the meeting plan automatically generated by number series.';
                }
                field("Committee Id"; Rec."Committee Id")
                {
                    ApplicationArea = All;
                    ToolTip = 'Select the board committee for this plan.';
                }
                field("Committee Description"; Rec."Committee Description")
                {
                    ApplicationArea = All;
                    ToolTip = 'Shows the description of the selected committee.';
                    QuickEntry = false;
                }
                field("Title"; Rec."Title")
                {
                    ApplicationArea = All;
                    ShowMandatory = true;
                    ToolTip = 'Enter the title of the meeting plan.';
                }
                field("Year"; Rec."Year")
                {
                    ApplicationArea = All;
                    ShowMandatory = true;
                    ToolTip = 'Enter the plan year.';
                }
                field("Quarter"; Rec."Quarter")
                {
                    ApplicationArea = All;
                    ShowMandatory = true;
                    ToolTip = 'Select the plan quarter.';
                }
                field("Status"; Rec."Status")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the lifecycle status of the meeting plan.';
                }
                field("Description"; Rec."Description")
                {
                    ApplicationArea = All;
                    MultiLine = true;
                    ToolTip = 'Enter additional descriptions or objectives for this plan.';
                }
                field("Created By"; Rec."Created By")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Displays the user who created this plan.';
                }
                field("Created At"; Rec."Created At")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Displays the timestamp when this record was created.';
                }
            }

            part(DateOptions; "Meeting Date Options Subform")
            {
                ApplicationArea = All;
                SubPageLink = "Meeting Plan Id" = field("Id");
            }

            group(PollResults)
            {
                Caption = 'Live Poll Votes';

                part(PollVotes; "Meeting Date Polls Subform")
                {
                    ApplicationArea = All;
                    Provider = DateOptions;
                    SubPageLink = "Meeting Date Option Id" = field("Id");
                }
            }
        }
    }
}